const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gitReview', {
  state: () => ipcRenderer.invoke('repo:state'),
  diff: (filePath, section) => ipcRenderer.invoke('repo:diff', filePath, section),
  stageFile: (filePath) => ipcRenderer.invoke('repo:stage-file', filePath),
  unstageFile: (filePath) => ipcRenderer.invoke('repo:unstage-file', filePath),
  discardFile: (filePath) => ipcRenderer.invoke('repo:discard-file', filePath),
  stageHunk: (patch) => ipcRenderer.invoke('repo:stage-hunk', patch),
  unstageHunk: (patch) => ipcRenderer.invoke('repo:unstage-hunk', patch),
  discardHunk: (patch) => ipcRenderer.invoke('repo:discard-hunk', patch),
  stageSelected: (patch, indexes, section) => ipcRenderer.invoke('repo:stage-selected', patch, indexes, section),
  commit: (message, amend) => ipcRenderer.invoke('repo:commit', message, amend),
  history: (limit) => ipcRenderer.invoke('repo:history', limit),
  commitDetails: (hash) => ipcRenderer.invoke('repo:commit-details', hash),
  remotes: () => ipcRenderer.invoke('repo:remotes'),
  branches: () => ipcRenderer.invoke('repo:branches'),
  fetch: () => ipcRenderer.invoke('repo:fetch'),
  pull: () => ipcRenderer.invoke('repo:pull'),
  push: () => ipcRenderer.invoke('repo:push'),
  undoCommit: () => ipcRenderer.invoke('repo:undo-commit'),
  addRemote: (name, url) => ipcRenderer.invoke('repo:add-remote', name, url),
  removeRemote: (name) => ipcRenderer.invoke('repo:remove-remote', name),
  switchBranch: (name) => ipcRenderer.invoke('repo:switch-branch', name),
  createBranch: (name) => ipcRenderer.invoke('repo:create-branch', name),
  onChanged: (callback) => ipcRenderer.on('repo:changed', (_event, state) => callback(state)),
  onError: (callback) => ipcRenderer.on('repo:error', (_event, error) => callback(error)),
});
