const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gitReview', {
  state: () => ipcRenderer.invoke('repo:state'),
  reviewState: () => ipcRenderer.invoke('review:state'),
  addReviewComment: (anchor, body) => ipcRenderer.invoke('review:add-comment', anchor, body),
  editReviewComment: (commentId, body) => ipcRenderer.invoke('review:edit-comment', commentId, body),
  resolveReviewComment: (commentId) => ipcRenderer.invoke('review:resolve-comment', commentId),
  diff: (filePath, section) => ipcRenderer.invoke('repo:diff', filePath, section),
  stageFile: (filePath) => ipcRenderer.invoke('repo:stage-file', filePath),
  unstageFile: (filePath) => ipcRenderer.invoke('repo:unstage-file', filePath),
  discardFile: (filePath) => ipcRenderer.invoke('repo:discard-file', filePath),
  stageHunk: (patch, filePath) => ipcRenderer.invoke('repo:stage-hunk', patch, filePath),
  unstageHunk: (patch, filePath) => ipcRenderer.invoke('repo:unstage-hunk', patch, filePath),
  discardHunk: (patch, filePath) => ipcRenderer.invoke('repo:discard-hunk', patch, filePath),
  stageSelected: (patch, indexes, section, filePath) => ipcRenderer.invoke('repo:stage-selected', patch, indexes, section, filePath),
  commit: (message, amend) => ipcRenderer.invoke('repo:commit', message, amend),
  history: (limit) => ipcRenderer.invoke('repo:history', limit),
  commitDetails: (hash) => ipcRenderer.invoke('repo:commit-details', hash),
  commitFileDiff: (hash, oldPath, filePath) => ipcRenderer.invoke('repo:commit-file-diff', hash, oldPath, filePath),
  remotes: () => ipcRenderer.invoke('repo:remotes'),
  branches: () => ipcRenderer.invoke('repo:branches'),
  fetch: () => ipcRenderer.invoke('repo:fetch'),
  pull: () => ipcRenderer.invoke('repo:pull'),
  push: () => ipcRenderer.invoke('repo:push'),
  undoCommit: () => ipcRenderer.invoke('repo:undo-commit'),
  addRemote: (name, url) => ipcRenderer.invoke('repo:add-remote', name, url),
  removeRemote: (name) => ipcRenderer.invoke('repo:remove-remote', name),
  switchBranch: (name) => ipcRenderer.invoke('repo:switch-branch', name),
  createBranch: (name) => ipcRenderer.invoke('repo:create-branch', name),
  onChanged: (callback) => ipcRenderer.on('repo:changed', (_event, state) => callback(state)),
  onReviewChanged: (callback) => ipcRenderer.on('review:changed', (_event, review) => callback(review)),
  onFocusComment: (callback) => ipcRenderer.on('review:focus-comment', (_event, commentId) => callback(commentId)),
  onError: (callback) => ipcRenderer.on('repo:error', (_event, error) => callback(error)),
});
